routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'Front\frontController@index')->name('welcome');
Route::get('/artGallery', 'Front\frontController@artGalley')->name('art.gallery');
Route::get('/ourArtist', 'Front\frontController@ourArtist')->name('our.artist');
Route::get('/detailart/{id}', 'Front\frontController@detail')->name('art.detail');
Route::get('/artisdetail/{id}', 'Front\frontController@artisdetail')->name('artis.detail');
Route::get('/aboutus', 'Front\frontController@aboutus')->name('about.us');

Route::get('/filterkategori/{id}', 'Front\frontController@filterkategori')->name('filter.kategori');

Route::post('/keranjangbeli', 'Front\frontController@keranjangbeli')->name('keranjangbeli');
Route::get('/keranjangsewa/{id}', 'Front\frontController@keranjangsewa')->name('keranjangsewa');

// Sewa
// Route::get('/keranjangsewa/{id}', 'Front\transaksiController@tambah_cart')->where('id', '[0-9]+');
// Route::get('/keranjangsewa/hapus/{id}', 'Front\transaksiController@hapus_cart')->where('id', '[0-9]+');
// ends sewa

Route::post('/postregister', 'Front\frontController@postregister')->name('post.register');
// Route::group(['middleware' => ['auth', 'CekRole:customer'], 'prefix' => 'Customer'], function () {
// 	Route::namespace('Front')->group(function () {

// 	});
// });

// Route::get('/registercompany', 'Auth\RegisterController@registercompany')->name('register.company');
// Route::get('/registerpersonal', 'Auth\RegisterController@registerpersonal')->name('register.personal');
// Route::post('postpersonal', 'Auth\RegisterController@postpersonal')->name('post.personal');
// Route::post('postcompany', 'Auth\RegisterController@postcompany')->name('post.company');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/AdminLap/dashboard', 'Front\frontController@adminlap')->name('adminlap');
// Route::get('/Management/dashboard', 'Front\frontController@management')->name('management');


Route::get('/province', 'Front\rajaOngkirController@get_province')->name('province');
Route::get('/kota/{id}', 'Front\rajaOngkirController@get_city')->name('city');
Route::get('/origin={city_origin}&destination={city_destination}&weight={weight}&courier={courier}', 'Front\rajaOngkirController@get_ongkir')->name('ongkir');


// Route::get('/cekkabupaten', 'Front\rajaOngkirController@index');



Route::group(['middleware' => ['auth', 'CekRole:customercompany,customerpersonal']], function () {
    Route::get('/MyDashboardPersonal', 'Front\customerController@index')->name('dashboard.customer');
    Route::get('/MyTransaksiPersonal', 'Front\customerController@tbelipersonal')->name('transaksi.beli.p');
    Route::get('/MyTransaksiSewa', 'Front\customerController@tsewa')->name('transaksi.sewa');
    Route::get('/SettingAkun', 'Front\customerController@settingakunp')->name('setting.akun.p');

    // transaksi
    Route::get('/ListKeranjangBeli', 'Front\transaksiController@listkeranjangbeli')->name('listkeranjangbeli');
    Route::get('/hapuscart/{key}', 'Front\transaksiController@hapuscart')->name('hapus.cart');
    Route::post('/ProsesBeli', 'Front\transaksiController@prosesbeli')->name('proses.orderbeli');

    Route::get('/ListKeranjangSewa', 'Front\transaksiController@listkeranjangsewa')->name('listkeranjangsewa');
    Route::get('/hapuscartsewa/{key}', 'Front\transaksiController@hapus_cart')->name('hapussewa');
    Route::post('/ProsesSewa', 'Front\transaksiController@prosessewa')->name('proses.ordersewa');
});

Route::group(['middleware' => ['auth', 'CekRole:superadmin'], 'prefix' => 'Superadmin'], function () {
    Route::namespace('Superadmin')->group(function () {
        Route::resource('kategoriproduk', 'kategoriProdukController');
        Route::resource('produk', 'produkController');
        Route::resource('pelukis', 'pelukisController')->parameters(['pelukis' => 'pelukis',]);
        Route::resource('ongkir', 'ongkirController');
        Route::resource('voucher', 'voucherController');
        Route::get('TransaksiBeli', 'TransaksiBeli@index')->name('t.beli.s');
        Route::get('DetailTransaksiBeli/{id}', 'TransaksiBeli@DetailBeli')->name('detailtransaksibeli');
        Route::get('KonfirmasiBeli/{id}', 'TransaksiBeli@konfirmasiBeli')->name('konfirmasi.beli');

        Route::get('TolakBeli/{id}', 'TransaksiBeli@TolakBeli')->name('tolakbeli');

        Route::get('TransaksiSewa', 'TransaksiSewa@index')->name('t.sewa.s');
        Route::get('DetailTransaksiSewa/{id}', 'TransaksiSewa@DetailSewa')->name('detailtransaksisewa');
        Route::get('KonfirmasiSewa/{id}', 'TransaksiSewa@konfirmasiSewa')->name('konfirmasi.sewa');
        Route::get('TolakSewa/{id}', 'TransaksiSewa@TolakSewa')->name('tolaksewa');
        Route::get('DataCustomer', 'CustomController@index')->name('customer');
        Route::get('UpdateDataCustomer/{id}', 'CustomController@updateindex')->name('index.update.customer');
        Route::patch('DataCustomer/update/{id}', 'CustomController@update')->name('update.customer');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:adminlap'], 'prefix' => 'AdminLap'], function () {
    Route::namespace('AdminLap')->group(function () {
        Route::get('TransaksiBeliMasuk', 'transaksibelimasuk@BeliMasuk')->name('belimasuk');
        Route::get('KonfirmasiKirimBeli/{id}', 'transaksibelimasuk@KonfirmasiKirimBeli')->name('konfirmasikirimBeli');
        Route::get('TransaksiSewaMasuk', 'transaksisewamasuk@SewaMasuk')->name('sewamasuk');
        Route::get('KonfirmasiKirimSewa/{id}', 'transaksisewamasuk@KonfirmasiKirimSewa')->name('konfirmasikirimSewa');
        
        // Route::get('TransaksiSewa', 'TransaksiSewa@index')->name('t.sewa.s');
        // Route::get('Konfirmasisewa/{id}', 'TransaksiSewa@konfirmasiSewa')->name('konfirmasi.sewa');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:manajemen'], 'prefix' => 'manajemen'], function () {
    Route::namespace('Manajemen')->group(function () {
        Route::get('Manajemen', 'manajemenController@index')->name('manajemen');
        Route::get('MTransaksiBeli', 'manajemenController@transaksibeli')->name('m.transaksi.beli');
        Route::get('MTransaksiBeli/{id}', 'manajemenController@detailtransaksibeli')->name('detail.m.beli');
        Route::get('MTransaksiSewa', 'manajemenController@transaksisewa')->name('m.transaksi.sewa');
        Route::get('MTransaksiSewa/{id}', 'manajemenController@detailtransaksisewa')->name('detail.m.sewa');
    });
});

// run artisan command
Route::get('/artisan', function () {
    Artisan::call('config:cache');
    Artisan::call('config:clear');
    Artisan::call('route:clear');
    Artisan::call('cache:clear');
    return 'OK';
});

app/Voucher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Voucher extends Model
{
    protected $fillable = [
        'namavoucher',
        'hargavoucher',
        'persen',
    ];
}

app/Http/Controllers/Superadmin/CustomController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CustomController extends Controller
{
    public function index(Request $request)
    {
        $data = User::where('role', 'customerpersonal')->orwhere('role', 'customercompany')->orderBy('id', 'desc')->paginate(5);
        // dd($data);

        if ($request->cari) {
            if ($request->cari == "customerpersonal") {
                $data = User::where('role')->orderBy('id', 'desc')->paginate(5);
            } elseif ($request->cari == "customercompany") {
                $data = User::where('role')->orderBy('id', 'desc')->paginate(5);
            } else {
                $data = User::where(function ($data) use ($request) {
                    $data->where('name', 'like', "%$request->cari%");
                    $data->orWhere('email', 'like', "%$request->cari%");
                })->orderBy('id', 'desc')->paginate(5);
            }
        }
        return view('Superadmin.dataCustomer.dataCustomer', compact('data'));
    }

    public function updateindex($id)
    {
        $data = User::with('userdetail')->get()->find($id);
        // dd($data);
        return view('Superadmin.dataCustomer.detailCustomer', compact('data'));
    }

    public function update(Request $request, $id)
    {
        // dd($request->all());
        DB::table('user_details')->where('user_id', $id)->update([
            'telpon' => $request->telpon,
            'latitude' => $request->latitude,
            'longitude' => $request->longitude,
            'premium' => $request->premium,
        ]);

        toast('Data Customer Berhasil Diperbaharui', 'success');
        return redirect()->route('customer');
    }
}

app/Http/Controllers/Superadmin/TransaksiBeli.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Produk;
use App\ReservasiBeli;
use App\UserDetail;
use Illuminate\Http\Request;

class TransaksiBeli extends Controller
{
    public function index()
    {
        $data = ReservasiBeli::with(['detailbeli', 'user'])->get();
        // dd($data);
        return view('Superadmin.Transaksi.index', compact('data'));
    }

    public function DetailBeli($id)
    {
        $data = ReservasiBeli::with('detailbeli')->get()->find($id);
        return view('Superadmin.Transaksi.Detail-Beli', compact('data'));
    }

    public function konfirmasiBeli($id)
    {
        $data = ReservasiBeli::with(['detailbeli', 'user'])->find($id);

        $data->update([
            'statuspembayaran' => 'Terbayar',
            'statuspengiriman' => 'Dikirim'
        ]);
        foreach ($data['detailbeli'] as $p) {
            $produk = Produk::find($p->id);
            $produk->update([
                'status' => 'terjual',
                'user_detail_id' => $data->user->userdetail['id'],
            ]);
        }

        toast('Data Beli Berhasil Dikonfirmasi', 'success');
        return redirect('Superadmin/TransaksiBeli');
    }

    public function TolakBeli($id)
    {
        $data = ReservasiBeli::with('detailbeli')->find($id);
        $data->update([
            'statuspembayaran' => 'Gagal',
            'statuspengiriman' => 'Dibatalkan'
        ]);
        foreach ($data['detailbeli'] as $p) {
            $produk = Produk::find($p->id);
            $produk->update([
                'status' => 'tersedia',
            ]);
        }
        toast('Transaksi Pembelian Ditolak', 'success');
        return redirect()->back();
    }
}

app/Http/Controllers/Superadmin/TransaksiSewa.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Produk;
use App\ReservasiSewa;
use Illuminate\Http\Request;

class TransaksiSewa extends Controller
{
    public function index()
    {
        $data = ReservasiSewa::with('detailsewa')->get();
        // dd($data);
        return view('Superadmin.Transaksi.sewa', compact('data'));
    }

    public function DetailSewa($id)
    {
        $data = ReservasiSewa::with('detailsewa')->find($id);
        return view('Superadmin.Transaksi.Detail-Sewa', compact('data'));
    }


    public function konfirmasiSewa($id)
    {
        $data = ReservasiSewa::with(['detailsewa', 'user'])->find($id);
        // dd($data->user->userdetail['id']);
        $data->update([
            'statuspembayaran' => 'Terbayar',
            'statuspengiriman' => 'Dikirim',
        ]);
        foreach ($data['detailsewa'] as $p) {
            $produk = Produk::find($p->id);
            // dd($produk);
            $produk->update([
                'status' => 'tersewa',
                'user_detail_id' => $data->user->userdetail['id'],
            ]);
        }

        toast('Data Sewa Berhasil Dikonfirmasi', 'success');
        return redirect('Superadmin/TransaksiSewa');
    }

    public function TolakSewa($id)
    {
        $data = ReservasiSewa::with('detailsewa')->find($id);
        $data->update([
            'statuspembayaran' => 'Gagal',
            'statuspengiriman' => 'Dibatalkan'
        ]);
        foreach ($data['detailsewa'] as $p) {
            $produk = Produk::find($p->id);
            $produk->update([
                'status' => 'tersedia',
            ]);
        }
        toast('Transaksi Sewa Ditolak', 'success');

        return redirect()->back();
    }
}

app/Http/Controllers/Superadmin/kategoriProdukController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Superadmin\KategoriProduk\KategoriProdukCreate;
use App\Http\Requests\Superadmin\KategoriProduk\KategoriProdukUpdate;
use App\KategoriProduk;
use App\Produk;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class kategoriProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = KategoriProduk::paginate(10);
        return view('Superadmin.KategoriProduk.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KategoriProdukCreate $request)
    {
        $data = $request->all();
        if($request->has('foto')){
            $foto = $request->foto;
            $new_foto = time() . 'kategori' . $foto->getClientOriginalName();
            $tujuan_uploud = 'uplouds/Kategori/';
            $foto->move($tujuan_uploud, $new_foto);
            $data['foto'] = $tujuan_uploud . $new_foto;
        }
        KategoriProduk::create($data);
        toast('Data Kategori Di Tambahkan','success');
        return redirect()->route('kategoriproduk.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(KategoriProduk $kategoriproduk)
    {
        return view('Superadmin.KategoriProduk.edit', compact('kategoriproduk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(KategoriProdukUpdate $request, KategoriProduk $kategoriproduk)
    {
        $data = $request->all();
        $data['foto'] = $kategoriproduk->foto;
        if($request->has('foto')){
            $foto = $request->foto;
            $new_foto = time() . 'kategori' . $foto->getClientOriginalName();
            $tujuan_uploud = 'uplouds/Kategori/';
            $foto->move($tujuan_uploud, $new_foto);
            $data['foto'] = $tujuan_uploud . $new_foto;
        }
        $kategoriproduk->update($data);
        toast('Data Kategori Di Update','success');
        return redirect()->route('kategoriproduk.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(KategoriProduk $kategoriproduk)
    {
        $cek = Produk::where('kategori_id', $kategoriproduk->id)->first();
        if(isset($cek)){
            alert()->info('Info','Data Kategori Di Gunakan Pada Produk');
            return redirect()->route('kategoriproduk.index');
        }
        $kategoriproduk->delete();
        toast('Data Kategori Di Hapus','error');
        return redirect()->route('kategoriproduk.index');
    }
}

resources/views/Superadmin/Voucher/edit.blade.php
@extends('layouts.stisla')

@section('content')
<div class="main-content">
    <div class="row justify-content-center">
        <div class="col-md-10 ml-5">
              <div class="row">
                <div class="col-md-12 text-center">
                    @foreach ($errors->all() as $error)
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>{{ $error }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endforeach
                </div>
              </div>
          <div class="card">
            <div class="card-header">
                <h4>Ubah Data Voucher {{ $voucher->namavoucher }}</h4>
            </div>
            <div class="card-body">
             <form action="{{ route('voucher.update', $voucher) }}" method="POST">
                 @csrf
                 @method('PUT')
                 <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Nama Voucher</label>
                    <input type="text" class="form-control" name="namavoucher" placeholder="nama voucher" value="{{ old('namavoucher', $voucher->namavoucher) }}">
                  </div>

                  <label for="exampleFormControlInput1" class="form-label">Harga</label>
                  <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">Rp</span>
                    <input type="number" name="hargavoucher" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" placeholder="harga voucher" value="{{ old('hargavoucher', $voucher->hargavoucher) }}">
                  </div>

                  <label for="exampleFormControlInput1" class="form-label">Persen</label>
                  <div class="input-group mb-3">
                    <input type="number" name="persen" class="form-control"  placeholder="persen diskon" value="{{ old('persen', $voucher->persen) }}">
                  </div>
                  
                 <div class="col-md-12 mb-5 text-center">
                     <button class="btn btn-primary">Simpan</button>
                 </div>
             </form>
            </div>
          </div>
        </div>
    </div>
</div>
@endsection

resources/views/Superadmin/Voucher/index.blade.php
@extends('layouts.stisla')

@section('content')
<div class="main-content">
    <div class="row">
        <div class="col-md-7 card">
            <div class="card-header">
                <h4>Semua Data Voucher</h4>
            </div>
            <div class="card-body">
                <table class="table text-center table-hover">
                    <thead>
                      <tr>
                        <th scope="col">No</th>
                        <th scope="col">Nama Voucher</th>
                        <th scope="col">Harga</th>
                        <th scope="col">Persen</th>
                        <th scope="col">Aksi</th>
                      </tr>
                    </thead>
                    <tbody>
                        @forelse ($data as $item => $voucher)
                            <tr>
                                <th scope="row">{{ $data->firstItem() + $item }}</th>
                                <td>{{ $voucher->namavoucher }}</td>
                                <td>
                                    Rp {{ number_format($voucher->hargavoucher) }}
                                </td>
                                <td>{{ $voucher->persen }} %</td>
                                <td>
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <b><i class="fas fa-ellipsis-v"></i></b>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                            <a href="{{ route('voucher.edit', $voucher) }}" class="dropdown-item">Edit</a>
                                            <form action="{{ route('voucher.destroy', $voucher) }}" method="POST" onsubmit="return confirm('Hapus Data, Anda Yakin ?')">
                                                {!! method_field('delete') . csrf_field() !!}
                                                <button class="dropdown-item" type="submit">
                                                    Delete
                                                </button>
                                            </form>
                                        </div>
                                </td>
                            </tr>
                        @empty
                            
                        @endforelse
                     
                    </tbody>
                  </table>
            </div>
        </div>
        <div class="col-md-5">
            <div class="row">
                <div class="col-md-12 text-center">
                    @foreach ($errors->all() as $error)
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>{{ $error }}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    @endforeach
                </div>
            </div>
          <div class="card">
            <div class="card-header">
                <h4>Tambah Data Voucher</h4>
            </div>
            <div class="card-body">
             <form action="{{ route('voucher.store') }}" method="POST">
                 @csrf
                 <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Nama Voucher</label>
                    <input type="text" class="form-control" name="namavoucher" placeholder="nama voucher" value="{{ old('namavoucher') }}">
                  </div>

                  <label for="exampleFormControlInput1" class="form-label">Harga</label>
                  <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">Rp</span>
                    <input type="number" name="hargavoucher" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" placeholder="harga voucher" value="{{ old('hargavoucher') }}">
                  </div>

                  <label for="exampleFormControlInput1" class="form-label">Persen</label>
                  <div class="input-group mb-3">
                    <input type="number" name="persen" class="form-control"  placeholder="persen diskon" value="{{ old('persen') }}">
                  </div>

                 <div class="col-md-12 mb-5 text-center">
                     <button class="btn btn-primary">Simpan</button>
                 </div>
             </form>
            </div>
          </div>
        </div>
    </div>
</div>
@endsection