routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'Front\frontController@index')->name('welcome');
Route::get('/artGallery', 'Front\frontController@artGalley')->name('art.gallery');
Route::get('/ourArtist', 'Front\frontController@ourArtist')->name('our.artist');
Route::get('/detailart/{id}', 'Front\frontController@detail')->name('art.detail');
Route::get('/artisdetail/{id}', 'Front\frontController@artisdetail')->name('artis.detail');
Route::get('/aboutus', 'Front\frontController@aboutus')->name('about.us');

Route::get('/filterkategori/{id}', 'Front\frontController@filterkategori')->name('filter.kategori');

Route::post('/keranjangbeli', 'Front\frontController@keranjangbeli')->name('keranjangbeli');
Route::get('/keranjangsewa/{id}', 'Front\frontController@keranjangsewa')->name('keranjangsewa');

// Sewa
// Route::get('/keranjangsewa/{id}', 'Front\transaksiController@tambah_cart')->where('id', '[0-9]+');
// Route::get('/keranjangsewa/hapus/{id}', 'Front\transaksiController@hapus_cart')->where('id', '[0-9]+');
// ends sewa

Route::post('/postregister', 'Front\frontController@postregister')->name('post.register');
// Route::group(['middleware' => ['auth', 'CekRole:customer'], 'prefix' => 'Customer'], function () {
// 	Route::namespace('Front')->group(function () {

// 	});
// });

// Route::get('/registercompany', 'Auth\RegisterController@registercompany')->name('register.company');
// Route::get('/registerpersonal', 'Auth\RegisterController@registerpersonal')->name('register.personal');
// Route::post('postpersonal', 'Auth\RegisterController@postpersonal')->name('post.personal');
// Route::post('postcompany', 'Auth\RegisterController@postcompany')->name('post.company');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/AdminLap/dashboard', 'Front\frontController@adminlap')->name('adminlap');
// Route::get('/Management/dashboard', 'Front\frontController@management')->name('management');


Route::get('/province', 'Front\rajaOngkirController@get_province')->name('province');
Route::get('/kota/{id}', 'Front\rajaOngkirController@get_city')->name('city');
Route::get('/origin={city_origin}&destination={city_destination}&weight={weight}&courier={courier}', 'Front\rajaOngkirController@get_ongkir')->name('ongkir');


// Route::get('/cekkabupaten', 'Front\rajaOngkirController@index');



Route::group(['middleware' => ['auth', 'CekRole:customercompany,customerpersonal']], function () {
    Route::get('/MyDashboardPersonal', 'Front\customerController@index')->name('dashboard.customer');
    Route::get('/MyTransaksiPersonal', 'Front\customerController@tbelipersonal')->name('transaksi.beli.p');
    Route::get('/MyTransaksiSewa', 'Front\customerController@tsewa')->name('transaksi.sewa');
    Route::get('/SettingAkun', 'Front\customerController@settingakunp')->name('setting.akun.p');

    // transaksi
    Route::get('/ListKeranjangBeli', 'Front\transaksiController@listkeranjangbeli')->name('listkeranjangbeli');
    Route::get('/hapuscart/{key}', 'Front\transaksiController@hapuscart')->name('hapus.cart');
    Route::post('/ProsesBeli', 'Front\transaksiController@prosesbeli')->name('proses.orderbeli');

    Route::get('/ListKeranjangSewa', 'Front\transaksiController@listkeranjangsewa')->name('listkeranjangsewa');
    Route::get('/hapuscartsewa/{key}', 'Front\transaksiController@hapus_cart')->name('hapussewa');
    Route::post('/ProsesSewa', 'Front\transaksiController@prosessewa')->name('proses.ordersewa');
});

Route::group(['middleware' => ['auth', 'CekRole:superadmin'], 'prefix' => 'Superadmin'], function () {
    Route::namespace('Superadmin')->group(function () {
        Route::resource('kategoriproduk', 'kategoriProdukController');
        Route::resource('produk', 'produkController');
        Route::resource('pelukis', 'pelukisController')->parameters(['pelukis' => 'pelukis',]);
        Route::resource('ongkir', 'ongkirController');
        Route::resource('voucher', 'voucherController');
        Route::get('TransaksiBeli', 'TransaksiBeli@index')->name('t.beli.s');
        Route::get('DetailTransaksiBeli/{id}', 'TransaksiBeli@DetailBeli')->name('detailtransaksibeli');
        Route::get('KonfirmasiBeli/{id}', 'TransaksiBeli@konfirmasiBeli')->name('konfirmasi.beli');

        Route::get('TolakBeli/{id}', 'TransaksiBeli@TolakBeli')->name('tolakbeli');

        Route::get('TransaksiSewa', 'TransaksiSewa@index')->name('t.sewa.s');
        Route::get('DetailTransaksiSewa/{id}', 'TransaksiSewa@DetailSewa')->name('detailtransaksisewa');
        Route::get('KonfirmasiSewa/{id}', 'TransaksiSewa@konfirmasiSewa')->name('konfirmasi.sewa');
        Route::get('TolakSewa/{id}', 'TransaksiSewa@TolakSewa')->name('tolaksewa');
        Route::get('DataCustomer', 'CustomController@index')->name('customer');
        Route::get('UpdateDataCustomer/{id}', 'CustomController@updateindex')->name('index.update.customer');
        Route::patch('DataCustomer/update/{id}', 'CustomController@update')->name('update.customer');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:adminlap'], 'prefix' => 'AdminLap'], function () {
    Route::namespace('AdminLap')->group(function () {
        Route::get('TransaksiBeliMasuk', 'transaksibelimasuk@BeliMasuk')->name('belimasuk');
        Route::get('KonfirmasiKirimBeli/{id}', 'transaksibelimasuk@KonfirmasiKirimBeli')->name('konfirmasikirimBeli');
        Route::get('TransaksiSewaMasuk', 'transaksisewamasuk@SewaMasuk')->name('sewamasuk');
        Route::get('KonfirmasiKirimSewa/{id}', 'transaksisewamasuk@KonfirmasiKirimSewa')->name('konfirmasikirimSewa');
        
        // Route::get('TransaksiSewa', 'TransaksiSewa@index')->name('t.sewa.s');
        // Route::get('Konfirmasisewa/{id}', 'TransaksiSewa@konfirmasiSewa')->name('konfirmasi.sewa');
    });
});

Route::group(['middleware' => ['auth', 'CekRole:manajemen'], 'prefix' => 'manajemen'], function () {
    Route::namespace('Manajemen')->group(function () {
        Route::get('Manajemen', 'manajemenController@index')->name('manajemen');
        Route::get('MTransaksiBeli', 'manajemenController@transaksibeli')->name('m.transaksi.beli');
        Route::get('MTransaksiBeli/{id}', 'manajemenController@detailtransaksibeli')->name('detail.m.beli');
        Route::get('MTransaksiSewa', 'manajemenController@transaksisewa')->name('m.transaksi.sewa');
        Route::get('MTransaksiSewa/{id}', 'manajemenController@detailtransaksisewa')->name('detail.m.sewa');
    });
});

// run artisan command
Route::get('/artisan', function () {
    Artisan::call('config:cache');
    Artisan::call('config:clear');
    Artisan::call('route:clear');
    Artisan::call('cache:clear');
    return 'OK';
});

resources/views/layouts/include/footerfront.blade.php
<section class="footer mt-5 mb-4">
    <div class="row justify-content-center">
        <div class="col-md-4 text-center">
            <b>LEARN MORE</b> <br>
            Panduan Pembelian <br>
            Panduan Sewa <br>
            Panduan Pembayaran
        </div>
        <div class="col-md-4 text-center">
            <b>CONTACT US</b> <br>
            Office   : Jl.Garuda No 89. Pringgolayan Bantul. Yogyakarta <br>
            Email   : indi@indi.com <br>
            Phone : 0277 987 0988
        </div>
        <div class="col-md-4 text-center">
            <b>CUSTOMER SERVICE</b> <br>
            Phone : 0277 987 0988
        </div>
    </div>
</section>

resources/views/layouts/include/navbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
      <ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        {{-- <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li> --}}
      </ul>
      {{-- <div class="search-element">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
        <button class="btn" type="submit"><i class="fas fa-search"></i></button>
        <div class="search-backdrop"></div>
        <div class="search-result">
          <div class="search-header">
            Histories
          </div>
          <div class="search-item">
            <a href="#">How to hack NASA using CSS</a>
            <a href="#" class="search-close"><i class="fas fa-times"></i></a>
          </div>
          <div class="search-item">
            <a href="#">Kodinger.com</a>
            <a href="#" class="search-close"><i class="fas fa-times"></i></a>
          </div>
          <div class="search-item">
            <a href="#">#Stisla</a>
            <a href="#" class="search-close"><i class="fas fa-times"></i></a>
          </div>
          <div class="search-header">
            Result
          </div>
          <div class="search-item">
            <a href="#">
              <img class="mr-3 rounded" width="30" src="{{ asset('assets') }}/img/products/product-3-50.png" alt="product">
              oPhone S9 Limited Edition
            </a>
          </div>
          <div class="search-item">
            <a href="#">
              <img class="mr-3 rounded" width="30" src="{{ asset('assets') }}/img/products/product-2-50.png" alt="product">
              Drone X2 New Gen-7
            </a>
          </div>
          <div class="search-item">
            <a href="#">
              <img class="mr-3 rounded" width="30" src="{{ asset('assets') }}/img/products/product-1-50.png" alt="product">
              Headphone Blitz
            </a>
          </div>
          <div class="search-header">
            Projects
          </div>
          <div class="search-item">
            <a href="#">
              <div class="search-icon bg-danger text-white mr-3">
                <i class="fas fa-code"></i>
              </div>
              Stisla Admin Template
            </a>
          </div>
          <div class="search-item">
            <a href="#">
              <div class="search-icon bg-primary text-white mr-3">
                <i class="fas fa-laptop"></i>
              </div>
              Create a new Homepage Design
            </a>
          </div>
        </div>
      </div> --}}
    </form>
    <ul class="navbar-nav navbar-right">
      {{-- <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link nav-link-lg message-toggle beep"><i class="far fa-envelope"></i></a>
        <div class="dropdown-menu dropdown-list dropdown-menu-right">
          <div class="dropdown-header">Messages
            <div class="float-right">
              <a href="#">Mark All As Read</a>
            </div>
          </div>
          <div class="dropdown-list-content dropdown-list-message">
            <a href="#" class="dropdown-item dropdown-item-unread">
              <div class="dropdown-item-avatar">
                <img alt="image" src="{{ asset('assets') }}/img/avatar/avatar-1.png" class="rounded-circle">
                <div class="is-online"></div>
              </div>
              <div class="dropdown-item-desc">
                <b>Kusnaedi</b>
                <p>Hello, Bro!</p>
                <div class="time">10 Hours Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item dropdown-item-unread">
              <div class="dropdown-item-avatar">
                <img alt="image" src="{{ asset('assets') }}/img/avatar/avatar-2.png" class="rounded-circle">
              </div>
              <div class="dropdown-item-desc">
                <b>Dedik Sugiharto</b>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                <div class="time">12 Hours Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item dropdown-item-unread">
              <div class="dropdown-item-avatar">
                <img alt="image" src="{{ asset('assets') }}/img/avatar/avatar-3.png" class="rounded-circle">
                <div class="is-online"></div>
              </div>
              <div class="dropdown-item-desc">
                <b>Agung Ardiansyah</b>
                <p>Sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <div class="time">12 Hours Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item">
              <div class="dropdown-item-avatar">
                <img alt="image" src="{{ asset('assets') }}/img/avatar/avatar-4.png" class="rounded-circle">
              </div>
              <div class="dropdown-item-desc">
                <b>Ardian Rahardiansyah</b>
                <p>Duis aute irure dolor in reprehenderit in voluptate velit ess</p>
                <div class="time">16 Hours Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item">
              <div class="dropdown-item-avatar">
                <img alt="image" src="{{ asset('assets') }}/img/avatar/avatar-5.png" class="rounded-circle">
              </div>
              <div class="dropdown-item-desc">
                <b>Alfa Zulkarnain</b>
                <p>Exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
                <div class="time">Yesterday</div>
              </div>
            </a>
          </div>
          <div class="dropdown-footer text-center">
            <a href="#">View All <i class="fas fa-chevron-right"></i></a>
          </div>
        </div>
      </li>
      <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>
        <div class="dropdown-menu dropdown-list dropdown-menu-right">
          <div class="dropdown-header">Notifications
            <div class="float-right">
              <a href="#">Mark All As Read</a>
            </div>
          </div>
          <div class="dropdown-list-content dropdown-list-icons">
            <a href="#" class="dropdown-item dropdown-item-unread">
              <div class="dropdown-item-icon bg-primary text-white">
                <i class="fas fa-code"></i>
              </div>
              <div class="dropdown-item-desc">
                Template update is available now!
                <div class="time text-primary">2 Min Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item">
              <div class="dropdown-item-icon bg-info text-white">
                <i class="far fa-user"></i>
              </div>
              <div class="dropdown-item-desc">
                <b>You</b> and <b>Dedik Sugiharto</b> are now friends
                <div class="time">10 Hours Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item">
              <div class="dropdown-item-icon bg-success text-white">
                <i class="fas fa-check"></i>
              </div>
              <div class="dropdown-item-desc">
                <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>
                <div class="time">12 Hours Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item">
              <div class="dropdown-item-icon bg-danger text-white">
                <i class="fas fa-exclamation-triangle"></i>
              </div>
              <div class="dropdown-item-desc">
                Low disk space. Let's clean it!
                <div class="time">17 Hours Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item">
              <div class="dropdown-item-icon bg-info text-white">
                <i class="fas fa-bell"></i>
              </div>
              <div class="dropdown-item-desc">
                Welcome to Stisla template!
                <div class="time">Yesterday</div>
              </div>
            </a>
          </div>
          <div class="dropdown-footer text-center">
            <a href="#">View All <i class="fas fa-chevron-right"></i></a>
          </div>
        </div>
      </li> --}}
      {{-- <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
        <img alt="image" src="{{ asset('assets') }}/img/avatar/avatar-1.png" class="rounded-circle mr-1">
        <div class="d-sm-none d-lg-inline-block">Hi, Ujang Maman</div></a>
        <div class="dropdown-menu dropdown-menu-right">
          <div class="dropdown-title">Logged in 5 min ago</div>
          <a href="features-profile.html" class="dropdown-item has-icon">
            <i class="far fa-user"></i> Profile
          </a>
          <a href="features-activities.html" class="dropdown-item has-icon">
            <i class="fas fa-bolt"></i> Activities
          </a>
          <a href="features-settings.html" class="dropdown-item has-icon">
            <i class="fas fa-cog"></i> Settings
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item has-icon text-danger">
            <i class="fas fa-sign-out-alt"></i> Logout
          </a>
        </div> --}}
      </li>
    </ul>
  </nav>

resources/views/layouts/include/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
      <div class="sidebar-brand">
        <a href="index.html">Ruang Pajang</a>
      </div>
      <div class="sidebar-brand sidebar-brand-sm">
        <a href="index.html">Rp</a>
      </div>

      <ul class="sidebar-menu">
        <li class="menu-header">Main Menu</li>
        <li class="nav-item {{ Request::is('home') ? 'active' : '' }}"><a class="nav-link" href="{{ route('home') }}"><i class="fas fa-fire"></i> <span>Dashboard</span></a></li>
        @can('isSuperadmin')
            <li class="nav-item {{ Request::is('Superadmin/kategoriproduk*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('kategoriproduk.index') }}"><i class="fas fa-fire"></i> <span>Kategori Produks</span></a></li>
            <li class="nav-item {{ Request::is('Superadmin/pelukis*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('pelukis.index') }}"><i class="fas fa-fire"></i> <span>Pelukis</span></a></li>
            <li class="nav-item {{ Request::is('Superadmin/produk*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('produk.index') }}"><i class="fas fa-fire"></i> <span>Produks</span></a></li>
            <li class="nav-item {{ Request::is('Superadmin/ongkir*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('ongkir.index') }}"><i class="fas fa-fire"></i> <span>Ongkir</span></a></li>
            <li class="nav-item {{ Request::is('Superadmin/voucher*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('voucher.index') }}"><i class="fas fa-fire"></i> <span>Voucher</span></a></li>
            <li class="nav-item {{ Request::is('Superadmin/TransaksiBeli*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('t.beli.s') }}"><i class="fas fa-fire"></i> <span>Transaksi Beli</span></a></li>
            <li class="nav-item {{ Request::is('Superadmin/TransaksiSewa*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('t.sewa.s') }}"><i class="fas fa-fire"></i> <span>Transaksi Sewa</span></a></li>
            <li class="nav-item {{ Request::is('Superadmin/DataCustomer*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('customer') }}"><i class="fas fa-fire"></i> <span>Data Customer</span></a></li>
        @endcan

        @can('isManajemen')
            <li class="nav-item {{ Request::is('manajemen/MTransaksiBeli*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('m.transaksi.beli') }}"><i class="fas fa-fire"></i> <span>Transaksi Beli</span></a></li>
            <li class="nav-item {{ Request::is('manajemen/MTransaksiSewa*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('m.transaksi.sewa') }}"><i class="fas fa-fire"></i> <span>Transaksi Sewa</span></a></li>
        @endcan
        


      </ul>

        <div class="mt-4 p-3 hide-sidebar-mini">
            <a class="btn btn-primary btn-lg btn-block btn-icon-split" href="{{ route('logout') }}"
            onclick="event.preventDefault();
            document.getElementById('logout-form').submit();">
             <i class="fas fa-sign-out-alt text-danger"></i> Logout
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>
    </aside>
  </div>